name: Issue Responder
on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to show this workflow was triggered
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue comment $ISSUE_URL --body "🤖 This workflow was triggered! Issue created by: ${{ github.event.issue.user.login }}"