name: Target Workflow
on:
  workflow_dispatch:

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Show this workflow was triggered
        run: |
          echo "🤖 Target workflow was triggered!"
          echo "Triggered by: ${{ github.actor }}"