name: Trigger Test
on:
  workflow_dispatch:

jobs:
  test-github-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push with GITHUB_TOKEN
        run: |
          echo "Test file $(date)" > github-token-test.txt
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Test with GITHUB_TOKEN"
          git push

  test-custom-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push with custom token
        run: |
          echo "Test file $(date)" > custom-token-test.txt
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Test with custom token"
          git remote set-url origin https://x-access-token:${{ secrets.MY_WORKFLOW_TOKEN }}@github.com/${{ github.repository }}.git
          git push