name: Trigger Test
on:
  workflow_dispatch:

jobs:
  test-github-token:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue with GITHUB_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create --repo ${{ github.repository }} --title "GITHUB_TOKEN test" --body "Should NOT trigger responder"

  test-custom-token:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue with custom token
        env:
          GH_TOKEN: ${{ secrets.MY_WORKFLOW_TOKEN }}
        run: |
          gh issue create --repo ${{ github.repository }} --title "Custom token test" --body "SHOULD trigger responder"